accounts/urls.py
from django.urls import path,include
from . import views
app_name = 'accounts'
urlpatterns = [
    # include default auth urls
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register, name='register'),
]

learning_logs/urls.py
'''learning logs urls'''
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # home page
    path('',views.index,name='index'),
    path('topics/',views.topics,name='topics'),
    path('topic/<int:topic_id>/',views.topic,name='topic'),
    path('new_topic/',views.new_topic,name = 'new_topic'),
    path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),
    path('topic/<int:topic_id>/delete/',views.delete_topic,name='delete_topic'),
    path('entry/<int:entry_id>/delete/',views.delete_entry,name='delete_entry'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('learning_logs.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    '''the topic the user is learning about'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        '''return a string representation of the model'''
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) >= 50:
            return f"{self.text[:50]}....."
        else:
            return self.text

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': '' }

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        lablels = {'text': '' }
        widgets = {'text':forms.Textarea(attrs={'placeholder':'Enter your text'})}

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # display blank regi. form
        form = UserCreationForm()
    else:
        # process completed form
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # log in and redirect
            login(request,new_user)
            return redirect('learning_logs:index')

    params = {'form':form}
    return render(request,'registration/register.html',params)

learning_logs/views.py
from django.shortcuts import render,redirect
from .models import Topic,Entry
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

def index(request):
    '''home page for learngin logs'''
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    '''topics page'''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
    '''single topic'''
    topic = Topic.objects.get(id=topic_id)
    # make sure topic belong to the current user.
    check_owner(request,topic)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

@login_required
def new_topic(request):
    '''add a new topic'''
    if request.method != 'POST':
        '''no data submitted; create a black form'''
        form = TopicForm()
    else:
        '''POST data submitted; process data'''
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # display a blank or invalid form.
    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    '''add new entry'''
    topic = Topic.objects.get(id=topic_id)
    check_owner(request,topic)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic',topic_id=topic_id)

    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
    '''edit existing entry.'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)

    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)
@login_required
def delete_topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method == 'POST':
        topic.delete()
        return redirect('learning_logs:topics')
    context = {'topic':topic}
    return render(request,'learning_logs/delete_topic.html',context)
@login_required
def delete_entry(request,entry_id):
    entry = Entry.objects.get(id=entry_id)
    if request.method == 'POST':
        entry.delete()
        return redirect('learning_logs:topics')
    context = {'entry':entry}
    return render(request,'learning_logs/delete_entry.html',context)

def check_owner(request,topic):
    if topic.owner != request.user:
        raise Http404

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="/static/learning_logs/styles.css">
    <title>Learning Log</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <!-- Account-related links -->
            <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text me-2">Hello, {{ user.username }}.
                    </span></li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">
                        Register</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        Log in</a></li>
                {% endif %}
            </ul> <!-- End of account-related links -->

            {% if user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}" method='post'>
                {% csrf_token %}
                <button name='submit' class='btn btn-outline-secondary btn-sm'>
                    Log out
                </button>
            </form>
            {% endif %}
        </div>
    </div>
</nav>
<main class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %} {% endblock content %}
    </div>
</main>
<br>
<footer>
    <p>&copy; 2024 Learning Log. All rights reserved.</p>
</footer>
</body>
</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% load static %}
    <link rel="stylesheet" type="text/css" href="/static/learning_logs/styles.css">

{% block page_header %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
        <li class="breadcrumb-item active" aria-current="page"> {{topic.text}}</li>
    </ol>
</nav>
<p>Are you Sure you want to delete this entry ?</p>
{% endblock page_header %}
{% block content %}
<form action="" method="post">
    {%csrf_token%}
    {% bootstrap_button button_type="submit" content="Yes,Delete" %}
</form>
<br>
<button class="cancel-link" onclick="goBack()">Cancel</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock content %}

learning_logs/templates/learning_logs/delete_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="/static/learning_logs/styles.css">
{% block page_header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Topics</li>
  </ol>
</nav>
<p>Confirm Deletion</p>
<p>Are you sure you want to delete '{{topic.text}}' ?</p>
{% endblock page_header %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_button button_type="submit" content="Yes,I'm sure" %}
</form>
<br>
<button class="cancel-link" onclick="goBack()">Cancel</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="/static/learning_logs/styles.css">
{% block page_header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
    <li class="breadcrumb-item active" aria-current="page"> {{topic.text}}</li>
  </ol>
</nav>
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit Entry</p>
{% endblock page_header %}
{% block content %}
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Save Changes" %}
</form>
<button class="backbutton" onclick="goBack()">Go Back</button>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Learning Log</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block page_header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Home</li>
  </ol>
</nav>
<div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
        <h1 class="display-3">Track your learning.</h1>
        <p class="lead">Learning log helps you keep track of your learning, for any topic you're interested.</p>
        {% if user.is_authenticated %}
        {% else %}
        <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
        {% endif %}
    </div>
</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="/static/learning_logs/styles.css">
{% load django_bootstrap5 %}
{% load static %}
    <link rel="stylesheet" href="{% static 'learning_logs/styles.css' %}">
{% block page_header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ topic.text }}</li>
  </ol>
</nav>
{% endblock page_header %}
{% block content %}
<h2>Add new Entry for {{ topic.text }}</h2>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add Entry" %}
</form>
<button class="backbutton" onclick="goBack()">Go Back</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="/static/learning_logs/styles.css">
{% block page_header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Topics</li>
  </ol>
</nav>
<p>Add a new Topic</p>
{% endblock page_header %}
{% block content %}
    <p>Add a new topic:</p>
    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add Topic" %}
    </form>

<button class="backbutton" onclick="goBack()">Go Back</button>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="/static/learning_logs/styles.css">
{% block page_header %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ topic.text }}</li>
    </ol>
</nav>
{% endblock page_header %}

{% block content %}
<h1>Topic: {{ topic.text }}</h1>
<h3>Entries:</h3>
<p>
    <a class="newpost" href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry : </a>
</p>

{% for entry in entries %}
<div class="card mb-3">
    <h4 class="card-header">
        {{ entry.date_added | date:'M d, Y H:i'}}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit Entry</a></small>
        <small><a href="{% url 'learning_logs:delete_entry' entry.id %}">Delete</a></small>
    </h4>
    <div class="card-body">{{ entry.text | linebreaks }}</div>
</div>
{% empty %}
    <p>No entries added yet.</p>
{% endfor %}

<a class="deletepost" href="{% url 'learning_logs:delete_topic' topic.id %}">Delete Topic</a><br>
<button class="backbutton" onclick="goBack()">Go Back</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="/static/learning_logs/styles.css">
{% block page_header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Topics</li>
  </ol>
</nav>
<h1>Topics</h1>
<br>
<div>
    <a class="newpost" href="{% url 'learning_logs:new_topic' %}">Add a new Post</a>
</div>
<br>
{% endblock page_header %}

{% block content %}
<div>
<ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
    <li class="list-group-item border-0">
        <div class="post-name">
        <a href="{% url 'learning_logs:topic' topic.id%}">
            {{ topic.text }}</a>
        </div>
    </li>
    {% empty %}
    <li class="list-group-item border-0">No posts added yet.</li>
    {% endfor %}
</ul>
</div>
<br>
<a class="backbutton" href="/">Go Back</a>
{% endblock content %}